### ISSUE TITLE
informative note about text should not include period

### ISSUE THREAD

**Issue by michaeldsmith** [SMPTE/st428-24#11]
Since the actual com marker text does not end with a period, I think the informative note that translates the bytes in the table to text should not end with a period

![image](https://github.com/SMPTE/st428-24/assets/37905569/ab31a5df-c107-4d98-95de-a69aca895781)

**Comment by palemieux** [comment]
The sentence must end with a period.

Three options:

- do nothing since this is an informative note and the table provides the normative definition as a byte string, specifically to avoid ambiguities

- surround the string with double quotes (`"`), which is ambiguous since it is not clear whether the double quotes are part of the string

- shade the string, just like the byte string.

What is your preference?

**Comment by michaeldsmith** [comment]
how about rephrasing the sentence so the byte string text does not end the sentence
change
The contents of the Ccom i bytes corresponds to the string SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1 .
to
The string SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1 corresponds to the contents of the Ccom i bytes .

**Comment by palemieux** [comment]
> The string SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1 corresponds to the contents of the Ccom i bytes .

That sentence is ambiguous.

**Comment by michaeldsmith** [comment]
is there another way that we can word it so the string text doesn't end the sentence?

**Comment by palemieux** [comment]
See improved rendering of code snippets
