### ISSUE TITLE
consider weaker file name extension requirements

### ISSUE THREAD

**Issue by michaeldsmith** [SMPTE/st428-24#9]
Since PDC files are also valid J2C codestreams, I think weaker normative language about file extension should be considered by the group.  I think allowing J2C file extension will increase compatibility of Packed DCDM with the broader JPEG 2000 ecosystem.  

Consider changing "shall" to "should" or "may"

![image](https://github.com/SMPTE/st428-24/assets/37905569/9f7c5070-6af7-4eb1-8490-777dd1766baa)

**Comment by DVDiva** [comment]
I’m open to the idea, but I think a few of the proponents should chime up if they have an issue with it.

Annie Chang (she/her)


From: michaeldsmith ***@***.***>
Date: Monday, June 12, 2023 at 7:16 AM
To: SMPTE/st428-24 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [SMPTE/st428-24] consider weaker file name extension requirements (Issue #9)

Since PDC files are also valid J2C codestreams, I think weaker normative language about file extension should be considered by the group. I think allowing J2C file extension will increase compatibility of Packed DCDM with the broader JPEG 2000 ecosystem.

Consider changing "shall" to "should" or "may"

[Image removed by sender. image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/37905569/245171033-9f7c5070-6af7-4eb1-8490-777dd1766baa.png__;!!PIZeeW5wscynRQ!tm-tkvAmPhyWyVxfx86NdtpslS0tJLf9js3Tl7EgbmQsSflPaPeA3JsYXp0TbezzzvJFFTCsp5prps_vLRjz0Zwuyw$>

**Comment by palemieux** [comment]
As a data point, Resolve supports file suffixes on import and export, but does not support the `pdc` file extension. I therefore suggest using `pdc` as a file suffix, to differentiate packed image files from lossy D-Cinema frames, and `j2c` as the extension, to maintain compatibility with tools.

See proposed redline at: https://doc.smpte-doc.org/st428-24-private/issues/0009-file-extension/pub-rl.html

**Comment by mikekrause35pm** [comment]
Concur with @michaeldsmith about conformance language in naming. Facilities may have internal naming spec for operator efficiency or automation, or more descriptive naming may be desired by a user.
Also, addition of ".pdc" as a moniker in file name will be redundant and may cause confusion with the final ".j2c" extension. A user seeing ".j2c" should know - through standard and spec - the difference in the pDCDM vs a TIFF-DCDM.

**Comment by michaeldsmith** [comment]
@mikekrause35pm if filename/naming-convention is going to be used, shouldn't we also make the COM marker text optional (SHOULD) instead of required (SHALL)?

**Comment by mikekrause35pm** [comment]
Also agree on COM. Like TIFF carrying metadata, great idea and would be super useful except implementation is sparse at best. Getting COM implemented and widespread might be a tough task.
IMO - naming of files should be a SHOULD (with examples presented) and COM should also be a SHOULD.
